language: android
jdk: oraclejdk8
sudo: true

os:
  - linux

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

script:
  - ./gradlew clean check --profile
